import type { MutableWebGLRenderStats } from "./MutableWebGLRenderStats.type.js";
import type { WebGLRenderStats } from "./WebGLRenderStats.type.js";

export function finalizeWebGLRenderStats(stats: MutableWebGLRenderStats): WebGLRenderStats {
  return {
    objects: stats.objects,
    renderList: stats.renderList,
    rects: stats.rects,
    arcs: stats.arcs,
    circles: stats.circles,
    ellipses: stats.ellipses,
    lines: stats.lines,
    polylines: stats.polylines,
    polygons: stats.polygons,
    shapePaths: stats.shapePaths,
    shapePathUnsupportedFills: stats.shapePathUnsupportedFills,
    sprites: stats.sprites,
    staticSprites: stats.staticSprites,
    dynamicSprites: stats.dynamicSprites,
    spriteBatches: stats.spriteBatches,
    staticSpriteBatches: stats.staticSpriteBatches,
    dynamicSpriteBatches: stats.dynamicSpriteBatches,
    spriteTextureGroups: stats.spriteTextureGroups,
    spriteTextureBinds: stats.spriteTextureBinds,
    sortedSpriteTextureBinds: stats.sortedSpriteTextureBinds,
    spriteTextureBindReduction: stats.spriteTextureBindReduction,
    skippedSpriteTextures: stats.skippedSpriteTextures,
    textures: stats.textures.size,
    textureBinds: stats.textureBinds,
    textureUploads: stats.textureUploads,
    textureCacheHits: stats.textureCacheHits,
    textTextures: stats.textTextures,
    textTextureCacheHits: stats.textTextureCacheHits,
    textTextureCacheMisses: stats.textTextureCacheMisses,
    textTextureEvictions: stats.textTextureEvictions,
    retiredTextTextures: stats.retiredTextTextures,
    batches: stats.batches,
    staticBatches: stats.staticBatches,
    dynamicBatches: stats.dynamicBatches,
    staticObjects: stats.staticObjects,
    dynamicObjects: stats.dynamicObjects,
    staticCacheHits: stats.staticCacheHits,
    staticCacheMisses: stats.staticCacheMisses,
    vertices: stats.vertices,
    drawCalls: stats.drawCalls,
    uploadBufferDataCalls: stats.uploadBufferDataCalls,
    uploadBufferSubDataCalls: stats.uploadBufferSubDataCalls,
    uploadedBytes: stats.uploadedBytes,
    unsupported: stats.unsupported
  };
}
