import type { RenderListStats } from "raw2d-core";

export interface MutableWebGLRenderStats {
  objects: number;
  renderList: RenderListStats;
  rects: number;
  arcs: number;
  circles: number;
  ellipses: number;
  lines: number;
  polylines: number;
  polygons: number;
  shapePaths: number;
  shapePathUnsupportedFills: number;
  sprites: number;
  staticSprites: number;
  dynamicSprites: number;
  spriteBatches: number;
  staticSpriteBatches: number;
  dynamicSpriteBatches: number;
  spriteTextureGroups: number;
  spriteTextureBinds: number;
  sortedSpriteTextureBinds: number;
  spriteTextureBindReduction: number;
  skippedSpriteTextures: number;
  textures: Set<string>;
  textureBinds: number;
  textureUploads: number;
  textureCacheHits: number;
  textTextures: number;
  textTextureCacheHits: number;
  textTextureCacheMisses: number;
  textTextureEvictions: number;
  retiredTextTextures: number;
  batches: number;
  staticBatches: number;
  dynamicBatches: number;
  staticObjects: number;
  dynamicObjects: number;
  staticCacheHits: number;
  staticCacheMisses: number;
  vertices: number;
  drawCalls: number;
  uploadBufferDataCalls: number;
  uploadBufferSubDataCalls: number;
  uploadedBytes: number;
  unsupported: number;
}
